library(tidyverse)
library(sf)
library(terra)
library(dplyr)
library(spData)
library(spDataLarge)
library(tmap)
library(leaflet) 
library(ggplot2)
power_plant = read_csv("California_Power_Plants.csv")
